// <auto-generated />
using System;
using Escuela_Api.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EscuelaApi.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    partial class AplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Escuela_Api.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido_Materno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Apellido_Paterno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Curp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Estado_Civil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Inicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha_Nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lugar_Nacimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nacionalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero_Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApellidoMaterno = "Canche",
                            ApellidoPaterno = "Lara",
                            Celular = "9831392917",
                            Correo = "claudetta910@gmail.com",
                            Curp = "LACC811009MQRRNL04",
                            Direccion = "Margarita Maza de Juarez #97",
                            Especialidad = "Informatica",
                            Estado = 1,
                            EstadoCivil = "Casada",
                            FechaInicio = new DateTime(2023, 9, 3, 2, 30, 20, 360, DateTimeKind.Local),
                            FechaNacimiento = new DateTime(1981, 10, 9, 2, 0, 50, 0, DateTimeKind.Local),
                            Genero = "Femenino",
                            LugarNacimiento = "Chetumal",
                            Nacionalidad = "Mexicana",
                            Nombres = "Claudia Maria",
                            NumeroMatricula = "123456",
                            Telefono = "9838324158"
                        },
                        new
                        {
                            Id = 2,
                            ApellidoMaterno = "Lara",
                            ApellidoPaterno = "Dzul",
                            Celular = "9831392917",
                            Correo = "JulietaDzul@gmail.com",
                            Curp = "DULJ110711MQRZRLA7",
                            Direccion = "Margarita Maza de Juarez #97",
                            Especialidad = "Diseñadora de modas",
                            Estado = 1,
                            EstadoCivil = "Soltera",
                            FechaInicio = new DateTime(2023, 9, 3, 2, 30, 20, 360, DateTimeKind.Local),
                            FechaNacimiento = new DateTime(2011, 7, 11, 4, 15, 50, 0, DateTimeKind.Local),
                            Genero = "Femenino",
                            LugarNacimiento = "Chetumal",
                            Nacionalidad = "Mexicana",
                            Nombres = "Julieta Montserrat",
                            NumeroMatricula = "123457",
                            Telefono = "9838324158"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
